from __future__ import annotations

FRUIT_EDUCATION = {
    "Apple": {
        "emoji": "🍎",
        "pronunciation": "AP-uhl",
        "speech": "Apple",
        "general": "An apple is a round fruit that can be red, green, or yellow. It grows on an apple tree. Apples are usually crisp and juicy inside.",
        "seed_title": "Apple seeds",
        "seed_description": "Apple seeds are small, smooth, brown, and slightly pointed. They sit inside the hard centre of the apple called the core.",
        "plant": "Tree",
        "weather": "Apple trees grow well where there are warm sunny growing seasons and a cooler winter period.",
        "soil": "Loose, fertile soil that drains water well. Loamy soil is a good example.",
        "water": "Young apple trees need regular watering. The soil should stay moist but not waterlogged.",
        "sun": "Apple trees like lots of sunlight, usually around 6 or more hours each day.",
        "growth_steps": [
            "A seed can sprout and grow roots.",
            "A young apple tree grows a stem, branches, and leaves.",
            "The tree makes flowers.",
            "After pollination, some flowers begin to become tiny apples.",
            "The apples grow bigger and ripen on the tree.",
        ],
        "photosynthesis": "The green leaves use sunlight, water from the roots, and carbon dioxide from the air to make sugar for the tree. This process is called photosynthesis.",
        "food": {
            "name": "Apple Yogurt Bowl",
            "steps": ["Ask an adult to cut apple into small pieces.", "Put plain yogurt in a bowl.", "Add the apple pieces.", "Sprinkle a little cinnamon if you like."],
        },
        "drink": {
            "name": "Apple Banana Smoothie",
            "steps": ["Add small apple pieces and half a banana to a blender.", "Add milk or yogurt.", "Ask an adult to blend until smooth.", "Pour into a cup and enjoy."],
        },
        "dessert": {
            "name": "Warm Cinnamon Apple",
            "steps": ["Ask an adult to slice an apple.", "Place the slices in a heat-safe dish.", "Add a small sprinkle of cinnamon.", "An adult can warm or bake the apple until soft."],
        },
        "safety": "Young children should have an adult cut firm apple pieces into an age-appropriate size to reduce choking risk.",
    },
    "Banana": {
        "emoji": "🍌",
        "pronunciation": "buh-NAN-uh",
        "speech": "Banana",
        "general": "A banana is a long, curved fruit with a peel. Most ripe bananas are yellow outside and soft and creamy inside.",
        "seed_title": "Banana seeds",
        "seed_description": "Most bananas sold for eating do not have large working seeds. The tiny dark dots inside are undeveloped seed traces. Farmers usually grow new banana plants from shoots called suckers that grow from the underground stem.",
        "plant": "Large herb, not a woody tree",
        "weather": "Bananas like warm, humid, tropical weather and do not grow well in frost.",
        "soil": "Rich, loose soil that holds some moisture but still drains well.",
        "water": "Banana plants need regular water because their large leaves lose lots of moisture.",
        "sun": "Banana plants grow best with plenty of sunlight and warmth.",
        "growth_steps": [
            "A new shoot grows from the underground stem.",
            "Large green leaves open and collect sunlight.",
            "A flower stalk grows from the centre of the plant.",
            "Small bananas form in groups called hands.",
            "The bananas grow bigger and ripen after harvesting or on the plant.",
        ],
        "photosynthesis": "Banana leaves catch sunlight. With water from the soil and carbon dioxide from the air, the leaves make sugar that helps the plant grow and fill its bananas.",
        "food": {
            "name": "Banana Toast",
            "steps": ["Place a slice of toast on a plate.", "Ask an adult to slice a banana.", "Put the banana slices on the toast.", "Add a thin layer of yogurt or seed/nut butter only if it is safe for the child."],
        },
        "drink": {
            "name": "Banana Milk Smoothie",
            "steps": ["Peel one banana.", "Put it in a blender with milk.", "Ask an adult to blend until smooth.", "Pour into a cup."],
        },
        "dessert": {
            "name": "Frozen Banana Bites",
            "steps": ["Ask an adult to slice a banana.", "Put the pieces on a plate or tray.", "Add a little yogurt if you like.", "Freeze until cold and firm, then allow to soften to an age-appropriate texture before eating."],
        },
        "safety": "An adult should prepare food for young children and check for allergies before using milk, yogurt, nuts, or seed butters.",
    },
    "Grape": {
        "emoji": "🍇",
        "pronunciation": "GRAYP",
        "speech": "Grape",
        "general": "Grapes are small round or oval fruits that grow together in bunches. They can be green, red, purple, or almost black.",
        "seed_title": "Grape seeds",
        "seed_description": "Some grapes have small hard seeds inside. They are usually tan or brown and can look a little like tiny pear-shaped stones. Seedless grapes have very small or undeveloped seeds.",
        "plant": "Climbing vine",
        "weather": "Grapevines like sunny growing seasons. Many varieties grow well in warm, fairly dry conditions once established.",
        "soil": "Well-drained soil is important because grape roots do not like sitting in water.",
        "water": "Young vines need regular watering. Older vines can often manage with less frequent deep watering, depending on the weather.",
        "sun": "Lots of direct sunlight helps grapes grow and become sweet.",
        "growth_steps": [
            "A young grapevine grows roots and climbing stems.",
            "Leaves spread out to collect sunlight.",
            "Tiny flowers grow in clusters.",
            "After pollination, the flowers become tiny grapes.",
            "The grapes grow in bunches and change colour as they ripen.",
        ],
        "photosynthesis": "Grape leaves use sunlight to make sugar. Some of that sugar travels into the grapes, helping them grow and taste sweet.",
        "food": {
            "name": "Safe Grape Yogurt Cup",
            "steps": ["An adult must cut grapes lengthwise into quarters for young children.", "Put yogurt in a cup or bowl.", "Add the safely cut grape pieces.", "Mix gently."],
        },
        "drink": {
            "name": "Grape Fruit Cooler",
            "steps": ["Ask an adult to cut seedless grapes safely.", "Blend the grapes with a little cold water.", "Strain if desired.", "Serve in a small cup."],
        },
        "dessert": {
            "name": "Grape Yogurt Pops",
            "steps": ["An adult cuts grapes safely into small pieces.", "Mix the pieces with yogurt.", "Spoon into a small ice-pop mould.", "Freeze and allow to soften to a safe texture before serving to a young child."],
        },
        "safety": "Whole grapes are a serious choking hazard for young children. An adult should cut grapes lengthwise into quarters before serving.",
    },
    "Mango": {
        "emoji": "🥭",
        "pronunciation": "MAN-go",
        "speech": "Mango",
        "general": "A mango is a sweet, juicy tropical fruit. Its skin may be green, yellow, orange, red, or a mixture of colours. The flesh inside is usually yellow or orange.",
        "seed_title": "Mango seed",
        "seed_description": "A mango has one very large, flat, hard seed in the middle. It is covered by a tough fibrous shell called a pit or stone.",
        "plant": "Evergreen tree",
        "weather": "Mango trees like warm tropical or subtropical weather and plenty of sunshine. Frost can damage them.",
        "soil": "Deep, well-drained soil works well. Mango roots do not like staying waterlogged.",
        "water": "Young mango trees need regular water. Established trees usually need less frequent watering, especially outside very dry periods.",
        "sun": "Mango trees need lots of direct sunlight to grow strongly and make fruit.",
        "growth_steps": [
            "A mango seed can sprout and send out roots.",
            "The young tree grows a trunk, branches, and long green leaves.",
            "Clusters of tiny flowers appear.",
            "Some flowers become baby mangoes after pollination.",
            "The mangoes grow larger and ripen on the tree.",
        ],
        "photosynthesis": "Mango leaves collect sunlight and use it with water and carbon dioxide to make sugar. The tree uses this food to grow leaves, roots, flowers, and mangoes.",
        "food": {
            "name": "Mango Yogurt Cup",
            "steps": ["Ask an adult to peel and cut mango into small pieces.", "Put yogurt in a bowl.", "Add the mango pieces.", "Mix gently."],
        },
        "drink": {
            "name": "Simple Mango Smoothie",
            "steps": ["Ask an adult to cut ripe mango flesh away from the pit.", "Put mango and milk or yogurt in a blender.", "Ask an adult to blend until smooth.", "Pour into a cup."],
        },
        "dessert": {
            "name": "Frozen Mango Yogurt",
            "steps": ["Mix small mango pieces with yogurt.", "Place the mixture in a freezer-safe container.", "Freeze until chilled and partly firm.", "Allow it to soften before serving."],
        },
        "safety": "The mango pit is hard and not edible. An adult should peel and cut mango for young children.",
    },
    "Strawberry": {
        "emoji": "🍓",
        "pronunciation": "STRAW-beh-ree",
        "speech": "Strawberry",
        "general": "A strawberry is a small red fruit with a green leafy top. It is soft, juicy, and usually has a sweet and slightly tangy taste.",
        "seed_title": "Strawberry seeds",
        "seed_description": "The tiny yellow, tan, or brown dots on the outside of a strawberry are called achenes. Each achene is a tiny fruit that contains a seed inside it.",
        "plant": "Small low-growing plant",
        "weather": "Strawberries like mild temperatures. Very hot or very cold weather can reduce fruit growth, depending on the variety.",
        "soil": "Loose, fertile, slightly acidic soil that drains well.",
        "water": "Strawberries need steady moisture, especially while flowers and fruits are growing. Water near the soil rather than soaking the fruit when possible.",
        "sun": "Strawberry plants usually produce best with plenty of sunlight.",
        "growth_steps": [
            "A strawberry plant grows roots and a crown near the soil.",
            "Green leaves spread out to catch sunlight.",
            "White flowers appear.",
            "After pollination, the centre of the flower grows into a strawberry.",
            "The strawberry becomes larger and changes from green to red as it ripens.",
        ],
        "photosynthesis": "Strawberry leaves use sunlight, water, and carbon dioxide to make sugar. This sugar helps the plant grow and helps the strawberries develop.",
        "food": {
            "name": "Strawberry Yogurt Sandwich",
            "steps": ["Ask an adult to slice strawberries thinly.", "Spread yogurt or soft cheese on bread.", "Add the strawberry slices.", "Close the sandwich and cut it into an age-appropriate size."],
        },
        "drink": {
            "name": "Strawberry Smoothie",
            "steps": ["Wash the strawberries and remove the green tops with adult help.", "Add strawberries and milk or yogurt to a blender.", "Ask an adult to blend until smooth.", "Pour into a cup."],
        },
        "dessert": {
            "name": "Strawberry Yogurt Parfait",
            "steps": ["Ask an adult to cut strawberries into small pieces.", "Put a layer of yogurt in a cup.", "Add strawberries.", "Repeat the layers and serve."],
        },
        "safety": "Wash strawberries before eating. An adult should cut them into an age-appropriate size for young children.",
    },
}


def fruit_names() -> list[str]:
    return list(FRUIT_EDUCATION.keys())
